image: maven:3.5-jdk-8

services:
- postgres:latest

variables:
  POSTGRES_DB: help_desk_dd
  POSTGRES_USER: root
  POSTGRES_PASSWORD: "root"
  POSTGRES_HOST: postgres
  DATABASE_URL: postgres://runner@localhost:5432/help_desk_dd

before_script:
# Install PG client & import schema info
- apt-get update && apt-get install -y postgresql-client libpq-dev
- PGPASSWORD=$POSTGRES_PASSWORD psql -U $POSTGRES_USER -h $POSTGRES_HOST -d $POSTGRES_DB -f db_Postgres.sql

stages:
- build
- deploy

build:
  stage: build
  artifacts:
    paths:
    - /builds/Vinty/help_desk/web/target/web.war
  script:
  - mvn package

deploy_dropbox:
  stage: deploy
  only:
  - master@Vinty/help_desk
  dependencies:
  - build
  variables:
    TARGET_FOLDER: "/Help_desk"
    UPLOADER_FETCH_URL: "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh"
    UPLOADER: "dropbox_uploader.sh"
    UPLOADER_CONFIG: "dropbox_uploader.cfg"
  before_script:
  - curl "${UPLOADER_FETCH_URL}" -o "${UPLOADER}"
  - echo "OAUTH_ACCESS_TOKEN=${DROPBOX_DEPLOY_TOKEN}" > "${UPLOADER_CONFIG}"
  script:
  - bash "${UPLOADER}" -f "${UPLOADER_CONFIG}" mkdir "${TARGET_FOLDER}" &>/dev/null || echo "Target folder exists"
  - bash "${UPLOADER}" -f "${UPLOADER_CONFIG}" upload /builds/Vinty/help_desk/web/target/web.war "${TARGET_FOLDER}"
  after_script:
  - rm -f "${UPLOADER}"
  - rm -f "${UPLOADER_CONFIG}"